# Generated by Django 3.2.25 on 2026-03-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0002_add_survey_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='game_type',
            field=models.CharField(default='prisoners-dilemma', max_length=50),
        ),
    ]
