# Generated by Django 3.2.25 on 2026-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0003_gamematch_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='player_1_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='player_2_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
