# Generated by Django 3.2.25 on 2026-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0004_auto_20260306_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='condition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='experiment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='label_a',
            field=models.CharField(default='Cooperate', max_length=50),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='label_b',
            field=models.CharField(default='Defect', max_length=50),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p1_cc',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p1_cd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p1_dc',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p1_dd',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p2_cc',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p2_cd',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p2_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='p2_dd',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='room_name',
            field=models.CharField(default="Prisoner's Dilemma", max_length=100),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='total_rounds',
            field=models.IntegerField(default=25),
        ),
    ]
