# Generated by Django 3.2.25 on 2026-02-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicGoodsGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(db_index=True, max_length=8)),
                ('round_number', models.PositiveIntegerField()),
                ('room_type', models.CharField(default='basic', max_length=20)),
                ('game_mode', models.CharField(default='online', max_length=10)),
                ('number_of_rounds', models.PositiveIntegerField(default=25)),
                ('endowment', models.PositiveIntegerField(default=20)),
                ('multiplier', models.FloatField(default=1.6)),
                ('punishment_cost', models.FloatField(default=1.0)),
                ('punishment_impact', models.FloatField(default=3.0)),
                ('reward_cost', models.FloatField(default=1.0)),
                ('reward_impact', models.FloatField(default=3.0)),
                ('current_stage', models.CharField(default='contribution', max_length=20)),
                ('is_match_complete', models.BooleanField(default=False)),
                ('player_1_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_2_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_3_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_4_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_1_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('player_2_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('player_3_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('player_4_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('player_1_country', models.CharField(default='Unknown', max_length=100)),
                ('player_2_country', models.CharField(default='Unknown', max_length=100)),
                ('player_3_country', models.CharField(default='Unknown', max_length=100)),
                ('player_4_country', models.CharField(default='Unknown', max_length=100)),
                ('player_1_city', models.CharField(default='Unknown', max_length=100)),
                ('player_2_city', models.CharField(default='Unknown', max_length=100)),
                ('player_3_city', models.CharField(default='Unknown', max_length=100)),
                ('player_4_city', models.CharField(default='Unknown', max_length=100)),
                ('player_1_contribution', models.FloatField(blank=True, null=True)),
                ('player_2_contribution', models.FloatField(blank=True, null=True)),
                ('player_3_contribution', models.FloatField(blank=True, null=True)),
                ('player_4_contribution', models.FloatField(blank=True, null=True)),
                ('player_1_payoff', models.FloatField(default=0)),
                ('player_2_payoff', models.FloatField(default=0)),
                ('player_3_payoff', models.FloatField(default=0)),
                ('player_4_payoff', models.FloatField(default=0)),
                ('total_contributions', models.FloatField(default=0)),
                ('group_return', models.FloatField(default=0)),
                ('player_1_cumulative_contribution', models.FloatField(default=0)),
                ('player_2_cumulative_contribution', models.FloatField(default=0)),
                ('player_3_cumulative_contribution', models.FloatField(default=0)),
                ('player_4_cumulative_contribution', models.FloatField(default=0)),
                ('player_1_cumulative_payoff', models.FloatField(default=0)),
                ('player_2_cumulative_payoff', models.FloatField(default=0)),
                ('player_3_cumulative_payoff', models.FloatField(default=0)),
                ('player_4_cumulative_payoff', models.FloatField(default=0)),
                ('action_type', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('round_started_at', models.DateTimeField(auto_now_add=True)),
                ('round_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Public Goods Game Data',
                'verbose_name_plural': 'Public Goods Game Data Logs',
                'ordering': ['match_id', 'round_number'],
                'unique_together': {('match_id', 'round_number')},
            },
        ),
    ]
