# Generated by Django 3.2.25 on 2026-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='endowment',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='is_match_complete',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='number_of_rounds',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='punishment_cost',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='punishment_impact',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='reward_cost',
        ),
        migrations.RemoveField(
            model_name='publicgoodsgamedata',
            name='reward_impact',
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='game_mode',
            field=models.CharField(default='online', max_length=20),
        ),
    ]
