# Generated by Django 3.2.25 on 2026-02-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0002_auto_20260206_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicGoodsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(db_index=True, max_length=8)),
                ('round_number', models.PositiveIntegerField()),
                ('actor_index', models.PositiveSmallIntegerField()),
                ('target_index', models.PositiveSmallIntegerField()),
                ('action_type', models.CharField(max_length=10)),
                ('amount', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Goods Action',
                'verbose_name_plural': 'Public Goods Actions',
                'ordering': ['match_id', 'round_number', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_1_stage1_payoff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_1_stage2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_2_stage1_payoff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_2_stage2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_3_stage1_payoff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_3_stage2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_4_stage1_payoff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='player_4_stage2_done',
            field=models.BooleanField(default=False),
        ),
    ]
