# Generated by Django 3.2.25 on 2026-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0003_auto_20260224_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='group_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='player_1_stage1_payoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='player_2_stage1_payoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='player_3_stage1_payoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='player_4_stage1_payoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicgoodsgamedata',
            name='total_contributions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
