# Generated by Django 3.2.25 on 2026-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0006_auto_20260226_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='condition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='endowment',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='experiment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='multiplier',
            field=models.FloatField(default=1.6),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='punishment_cost',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='punishment_value',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='reward_cost',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='reward_value',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='publicgoodsgamedata',
            name='total_rounds',
            field=models.IntegerField(default=25),
        ),
    ]
