# Generated by Django 3.2.25 on 2026-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='condition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='experiment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='punishment_cost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='punishment_value',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='reward_cost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='commonpoolgamedata',
            name='reward_value',
            field=models.FloatField(default=4.0),
        ),
    ]
