# Generated by Django 3.2.25 on 2026-03-27 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('game_type', models.CharField(choices=[('prisoner', '2x2 Economic Games'), ('ultimatum', 'Ultimatum Game'), ('public_goods', 'Public Goods Game')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUltimatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('endowment', models.IntegerField(default=100)),
                ('rounds', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum_conditions', to='custom_rooms.customexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPublicGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(default='basic', max_length=50)),
                ('endowment', models.IntegerField(default=20)),
                ('multiplier', models.FloatField(default=1.6)),
                ('rounds', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_goods_conditions', to='custom_rooms.customexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPrisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255)),
                ('payoff_matrix', models.JSONField(default=dict)),
                ('rounds', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prisoner_conditions', to='custom_rooms.customexperiment')),
            ],
        ),
    ]
