# Generated by Django 3.2.25 on 2026-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprisoner',
            name='payoff_matrix',
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p1_cc',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p1_cd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p1_dc',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p1_dd',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p2_cc',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p2_cd',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p2_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='p2_dd',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='room_name',
            field=models.CharField(default="Prisoner's Dilemma", max_length=255),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='punishment_cost',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='punishment_value',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='reward_cost',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='reward_value',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='customultimatum',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customultimatum',
            name='switch_roles',
            field=models.BooleanField(default=True),
        ),
    ]
