# Generated by Django 3.2.25 on 2026-03-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_rooms', '0002_auto_20260327_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexperiment',
            name='creator_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='creator_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='creator_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customultimatum',
            name='creator_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customexperiment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_experiments', to=settings.AUTH_USER_MODEL),
        ),
    ]
