# Generated by Django 3.2.25 on 2026-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0003_auto_20260327_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprisoner',
            name='experiment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='experiment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customultimatum',
            name='experiment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
