# Generated by Django 3.2.25 on 2026-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0004_auto_20260327_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexperiment',
            name='game_type',
            field=models.CharField(choices=[('prisoner', '2x2 Game'), ('ultimatum', 'Ultimatum'), ('public_goods', 'Public Goods')], max_length=50),
        ),
    ]
