# Generated by Django 3.2.25 on 2026-03-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0005_alter_customexperiment_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customultimatum',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='customultimatum',
            name='switch_roles',
        ),
    ]
