# Generated by Django 3.2.25 on 2026-04-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0006_auto_20260327_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexperiment',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='custompublicgoods',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customultimatum',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
