# Generated by Django 3.2.25 on 2026-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0007_auto_20260401_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprisoner',
            name='label_a',
            field=models.CharField(default='Cooperate', max_length=100),
        ),
        migrations.AddField(
            model_name='customprisoner',
            name='label_b',
            field=models.CharField(default='Defect', max_length=100),
        ),
    ]
