# Generated by Django 3.2.25 on 2026-06-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0008_auto_20260420_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexperiment',
            name='game_type',
            field=models.CharField(choices=[('prisoner', '2x2 Game'), ('ultimatum', 'Ultimatum'), ('public_goods', 'Public Goods'), ('common_pool', 'Common-Pool Resource')], max_length=50),
        ),
        migrations.CreateModel(
            name='CustomCommonPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_username', models.CharField(blank=True, max_length=150, null=True)),
                ('experiment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_code', models.CharField(blank=True, max_length=6, null=True)),
                ('condition_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(default='basic', max_length=50)),
                ('initial_fish_stock', models.IntegerField(default=100)),
                ('max_fish_stock', models.IntegerField(default=100)),
                ('max_extraction', models.IntegerField(default=10)),
                ('final_bonus_multiplier', models.FloatField(default=0.4)),
                ('rounds', models.IntegerField(default=20)),
                ('reward_cost', models.FloatField(default=1.0)),
                ('reward_value', models.FloatField(default=4.0)),
                ('punishment_cost', models.FloatField(default=1.0)),
                ('punishment_value', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_pool_conditions', to='custom_rooms.customexperiment')),
            ],
        ),
    ]
