# Generated by Django 3.2.25 on 2026-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0009_auto_20260623_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customultimatum',
            name='game_type',
            field=models.CharField(choices=[('iterative', 'Iterative'), ('one_shot', 'One Shot')], default='iterative', max_length=20),
        ),
    ]
