# Generated by Django 6.0.7 on 2026-07-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_rooms', '0010_customultimatum_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('investigator', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('ethics_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_number', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('participation_type', models.CharField(default='voluntary', max_length=50)),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, null=True)),
                ('compensation_enabled', models.BooleanField(default=False)),
                ('compensation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('compensation_description', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('data_collected', models.TextField()),
                ('data_access', models.TextField()),
                ('post_experiment_survey', models.BooleanField(default=True)),
                ('storage_duration', models.CharField(max_length=50)),
                ('future_use', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_form', to='custom_rooms.customexperiment')),
            ],
        ),
    ]
