# Generated by Django 3.2.25 on 2025-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_game_theory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_meditation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_meditation_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_punitive_God',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_1_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_game_theory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_meditation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_meditation_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_punitive_God',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='player_2_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
