# Generated by Django 3.2.25 on 2026-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0002_add_survey_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimatumgameround',
            name='condition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='endowment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='experiment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ultimatumgameround',
            name='total_rounds',
            field=models.IntegerField(default=25),
        ),
    ]
