# Generated by Django 3.2.25 on 2026-04-20 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0003_auto_20260420_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimatumgameround',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
