# Generated by Django 3.2.25 on 2026-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0004_ultimatumgameround_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimatumgameround',
            name='game_type',
            field=models.CharField(choices=[('iterative', 'Iterative'), ('one_shot', 'One Shot')], default='iterative', max_length=20),
        ),
    ]
